### ISSUE TITLE
Github > README.me

### ISSUE THREAD

**Issue by johannpinson** [JulienWszolek/hetic-p2020-04#6]
Make some changes to improve the README.md :

- [x] Use section to discern the different parts, with at least this minimal 3 parts "how to" : Installation, Running and Building the app
- [x] Add precision about (S)CSS naming convention (BEM ? OCCSS ? etc.)
- [x] So don't forget to specify any requirement (node.js >= 6.4 ? npm -g yarn ? etc.)
- [ ] You can add anything else useful (credit, git commit msg convention, badge, logo, screenshot, etc.)

**Comment by johannpinson** [comment]
test

**Comment by johannpinson** [comment]
Comment to re-push on slack channel

**Comment by JulienWszolek** [comment]
Ok it's done ✅
