### ISSUE TITLE
NPM > Dependencies management

### ISSUE THREAD

**Issue by johannpinson** [JulienWszolek/hetic-p2020-04#9]
Don't say to use both npm or yarn for the install, because the files yarn.lock and package-lock.json may not be at the same version.

- [ ] Choose package-lock or yarn.lock to manage the depencies (cf. yarnpkg/yarn#3614)

**Comment by JulienWszolek** [comment]
I said npm or yarn, in order to indicate you can have the choice between npm / yarn

**Comment by johannpinson** [comment]
Yes but no choice allowed because you may have difference between the `yarn.lock` and `package-lock.json`

Look at the conversation to the link indicated inside the first comment.
